default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: omwomo97
  password: Omwomo97
  host: localhost
  port: 5432

development:
  <<: *default
  database: booking_cap_db
test:
  <<: *default
  database: booking_cap_db

production:
  <<: *default
  database: booking_cap_db
