default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 11223344
  host: localhost
  port: 5432

development:
  <<: *default
  database: fullstackbackend
  
test:
  <<: *default
  database: fullstackbackend

production:
  <<: *default
  database: fullstackbackend